spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: 1000

https:
  port: 9443
  ssl:
    key-store: tomcat.keystore
    key-store-password: 123456
server:
  port: 6666